### ISSUE TITLE
Android Studio Runtime Error

### ISSUE THREAD

**Issue by amarz2195** [hussien89aa/AndroidTutorialForBeginners#38]
Hello sir. I am quite new with android studio.
I have built the project without error.
Also have sync the gradle file with the project successfully.

But when I try to run the Android Studio project, it shows error.
It says that there is no APK file build for the project even though I have build the APK for the project
It also cannot find ID for the project
what should I do?

**Comment by sofiane-jell** [comment]
bro you sent a email wrong i have not any information about android

**Comment by amarz2195** [comment]
okay bro. thank you for the reply
